# Generated by Django 4.0.4 on 2022-09-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_horario_seccion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenalumno',
            name='token',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
