# Generated by Django 4.0.4 on 2022-09-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tokenalumno_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='fecha_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokenalumno',
            name='fecha_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
