# Generated by Django 4.0.4 on 2022-09-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_codigoqr_fecha_exp_alter_tokenalumno_fecha_exp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenalumno',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
