# Generated by Django 4.0.4 on 2022-09-03 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_token_id_tokenalumno_tokenalumno_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenalumno',
            name='alumno_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.alumno'),
        ),
    ]
