# Generated by Django 4.0.4 on 2022-09-03 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tokenalumno_alumno_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenalumno',
            name='alumno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.alumno'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tokenlogin',
            name='alumno_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.alumno'),
        ),
    ]
