# Generated by Django 4.0.4 on 2022-09-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tokenlogin_verificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenlogin',
            name='alumno_id',
        ),
        migrations.AddField(
            model_name='tokenlogin',
            name='usuario',
            field=models.CharField(default='alva.arenas', max_length=100),
            preserve_default=False,
        ),
    ]
