# Generated by Django 4.0.4 on 2022-09-04 00:38

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_tokenlogin_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='fecha_exp',
            field=models.DateTimeField(default=core.models.exp_date),
        ),
        migrations.AlterField(
            model_name='codigoqr',
            name='url',
            field=models.CharField(default=core.models.tokenize, max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenalumno',
            name='fecha_exp',
            field=models.DateTimeField(default=core.models.exp_date),
        ),
        migrations.AlterField(
            model_name='tokenalumno',
            name='token',
            field=models.CharField(blank=True, default=core.models.tokenize, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenlogin',
            name='fecha_exp',
            field=models.DateTimeField(default=core.models.exp_date),
        ),
        migrations.AlterField(
            model_name='tokenlogin',
            name='token',
            field=models.CharField(blank=True, default=core.models.tokenize, max_length=1000, null=True, unique=True),
        ),
    ]
